### ISSUE TITLE
decompressFrame expects the frames to be upside down vs. what datashader outputs

### ISSUE THREAD

**Issue by hamilton** [mdboom/minishader-experiment#5]
I may have this problem wrong, but it appears that datashader either outputs the xdarray upside-down, or my coercion to `np.matrix` does (for now I am just calling `numpy.flip(agg, axis=0)` which works fine, or `decompressFrame` does. The gif below shows the 311 calls floating out between marin and sf.

![broken-311-map](https://user-images.githubusercontent.com/95735/54801744-917e8680-4c25-11e9-89a4-862794142b2b.gif)

**Comment by mdboom** [comment]
Yeah, matrices are always upside down to arrays (guess it's a linear algebra thing), so flipping it back is expected, unfortunately.
